#!/usr/bin/env python3

from sys import argv, exit
import math
from math import *


def main():
    angle = 0
    if len(argv) != 8:
            print("Bad length of arguments")
            return 84
    if (argv[1] == '-h'):
        print("USAGE")
        print("    ./101pong x0 y0 z0 x1 y1 z1 n\n")
        print("DESCRIPTION")
        print("    x0 ball abscissa at time t - 1")
        print("    y0 ball ordinate at time t - 1")
        print("    z0 ball altitude at time t - 1")
        print("    x1 ball abscissa at time t")
        print("    y1 ball ordinate at time t")
        print("    z1 ball altitude at time t")
        print("    n  time shift (greater than or equal to zero, integer)")
        return 84

    if (argv[1] != "-h"):
        try:
            x0 = float(argv[1])
            y0 = float(argv[2])
            z0 = float(argv[3])
            x1 = float(argv[4])
            y1 = float(argv[5])
            z1 = float(argv[6])
            n = int(argv[7])

        except ValueError:
            print("Arguments must be numbers")
            return 84
        if n < 0:
            print("n must be positive")
            return 84

        calcul0 = z1 - z0
        calcul1 = x1 - x0
        calcul2 = y1 - y0
        calcul3 = z1 - z0
        angle = 90 - (acos(abs(calcul0) / sqrt(pow(calcul1, 2) + pow(calcul2, 2) + pow(calcul3, 2)))) * 180 / math.pi
        print("The velocity vector of the ball is:")
        print("(%.2f, %.2f, %.2f)" %(x1-x0, y1-y0, z1-z0))
        print("At time t + %d, ball coordinates will be:" %n)
        print ("(%.2f, %.2f, %.2f)" %(x1+n*(x1-x0), y1+n*(y1-y0), z1+n*(z1-z0)))

        if ((z1 - z0 == 0) & (z1 != 0)):
            print("The ball won't reach the paddle.")
            return 0
        if (-z1 /(z1 - z0) < 0):
            print("The ball won't reach the paddle.")
            return 0
        if angle <= 0 or angle >= 90:
            print("Angle should be between 0 and 90")
            return 84
        print("The incidence angle is:")
        print ("%.2f degrees" % angle)
        return 0

if __name__ == "__main__":
    exit(main()) 